### ISSUE TITLE
11. Desarrollar el manejo de errores y excepciones en los puntos finales de la API

### ISSUE THREAD

**Issue by augustobritos** [CodeSystem2022/e-commerce-los-borbocoders#11]
Tareas a Realizar:
1. Identificar los puntos finales (endpoints) que requieren manejo de errores y excepciones.
2. Diseñar estrategias de manejo de errores adecuadas para cada punto final, si es posible incorporar loggers para el registro de eventos relevantes.
3. Implementar el manejo de errores en el código de la API.

**Comment by Axelforn** [comment]
Se aplicaron mejoras en el código.
